export const webSecurityVideosAndArticles = [
  {
    id: "dssd53",
    type: "video",
    category: "Основни безбедносни принципи",
    title: "Како да заштитите свој веб сајт од напада",
    text: "Овој видео го истражува важниот принцип заштите на вашиот веб сајт од различни видови на напади, вклучувајќи SQL, XSS напади и CSRF напади.",
    datePosted: "18.04.2024",
    comments: [
      {
        comment: "Браво, фантастично изведено!",
        userImage: "../../assets/imgProfile/profile14.png",
        userName: "Никола Трајковски",
        dateComment: "23.05.2024, 17:03",
      },
      {
        comment: "Фантастично, одлично!",
        userImage: "../../assets/imgProfile/profile13.png",
        userName: "Елена Ангелова",
        dateComment: "23.05.2024, 17:05",
      },
    ],
    URL: "../../assets/filterSection/video4.mp4",
  },
  {
    id: "kjkxcksd",
    type: "article",
    category: "Најпопуларни",
    title: "Како да се заштитите од социјални инженери",
    text: "Овој дел ги претставува најефективните начини за заштита од социјални инженери и како да се заштитите од превари кои можат да влијаат на вашата приватност и безбедност.",
    datePosted: "12.05.2024",
    comments: [
      {
        comment: "Изумително, страхотно!",
        userImage: "../../assets/imgProfile/profile1.png",
        userName: "Марија Ѓорѓиева",
        dateComment: "23.05.2024, 17:08",
      },
      {
        comment: "Одлично, продолжете така!",
        userImage: "../../assets/imgProfile/profile2.png",
        userName: "Александар Петковски",
        dateComment: "23.05.2024, 17:10",
      },
      {
        comment: "Браво, одлично изведено!",
        userImage: "../../assets/imgProfile/profile13.png",
        userName: "Јована Стефановска",
        dateComment: "23.05.2024, 17:13",
      },
      {
        comment: "Фантастично, вистински уживање!",
        userImage: "../../assets/imgProfile/profile2.png",
        userName: "Мартин Трајков",
        dateComment: "23.05.2024, 17:15",
      },
    ],
    URL: "../../assets/filterSection/9.jpg",
  },
  {
    id: "sdhgdj673",
    type: "video",
    category: "Заштита од малвери и вируси",
    title: "Како да детектирате и уклоните малвер од својот веб сајт",
    text: "Ова видео објаснува како да детектирате и оттргнете малверски код во вашата веб апликација и како да го заштитите вашиот сајт од потенцијални малверски напади.",
    datePosted: "15.04.2024",
    comments: [
      {
        comment: "Браво, фантастично!",
        userImage: "../../assets/imgProfile/profile6.png",
        userName: "Стефан Димитровски",
        dateComment: "23.05.2024, 16:55",
      },
      {
        comment: "Фантастично, уживај!",
        userImage: "../../assets/imgProfile/profile7.png",
        userName: "Ангела Миланова",
        dateComment: "23.05.2024, 16:58",
      },
      {
        comment: "Одлично, продолжете вака!",
        userImage: "../../assets/imgProfile/profile13.png",
        userName: "Марија Димитрова",
        dateComment: "23.05.2024, 17:00",
      },
    ],
    URL: "../../assets/filterSection/video2.mp4",
  },
  {
    id: "ghe348",
    type: "video",
    category: "Заштита на податоците",
    title: "Како да заштитите приватноста на корисниците на вашиот веб сајт",
    text: "Ова видео објаснува важноста на заштитата на приватноста на корисниците и како да го избегнете кршењето на приватноста на податоците.",
    datePosted: "20.04.2024",
    comments: [
      {
        comment: "Одлично, страхотно изведено!",
        userImage: "../../assets/imgProfile/profile5.png",
        userName: "Јована Петкова",
        dateComment: "23.05.2024, 16:53",
      },
    ],
    URL: "../../assets/filterSection/video7.mp4",
  },
  {
    id: "jhhjdaa76ada",
    type: "article",
    category: "Најпопуларни",
    title: "Најчестите видови на онлајн претплатнички измами",
    text: "Овој дел ги идентификува и објаснува најчестите видови на онлајн претплатнички измами и како да ги препознаете.",
    datePosted: "05.05.2024",
    comments: [
      {
        comment: "Фантастично, продолжете вака!",
        userImage: "../../assets/imgProfile/profile9.png",
        userName: "Наташа Ангелова",
        dateComment: "23.05.2024, 17:28",
      },
    ],
    URL: "../../assets/filterSection/7.jpg",
  },
  {
    id: "sdgh2h37d",
    type: "video",
    category: "Основни безбедносни принципи",
    title: "Користење на HTTPS за заштита на комуникацијата",
    text: "Ова видео објаснува зошто е важно користењето на HTTPS за заштита на приватноста и безбедноста на вашата веб страница и комуникацијата со корисниците.",
    datePosted: "22.04.2024",
    comments: [
      {
        comment: "Фантастично, уживајте!",
        userImage: "../../assets/imgProfile/profile3.png",
        userName: "Владимир Јорданов",
        dateComment: "23.05.2024, 16:50",
      },
    ],
    URL: "../../assets/filterSection/video1.mp4",
  },
  {
    id: "f8ddhf29",
    type: "video",
    category: "Заштита од малвери и вируси",
    title: "Како да спречите инфекција од злонамерен софтвер",
    text: "Ова видео ги дава советите за спречување на инфекција од различни видови на злонамерен софтвер како што се вируси, тројанци и други малверски програми.",
    datePosted: "25.04.2024",
    comments: [
      {
        comment: "Фантастично, продолжете вака!",
        userImage: "../../assets/imgProfile/profile1.png",
        userName: "Ивана Николова",
        dateComment: "23.05.2024, 16:43",
      },
      {
        comment: "Одлично, фантастично!",
        userImage: "../../assets/imgProfile/profile11.png",
        userName: "Јана Ангеловска",
        dateComment: "23.05.2024, 16:45",
      },
      {
        comment: "Браво, одлично изведено!",
        userImage: "../../assets/imgProfile/profile12.png",
        userName: "Анастасија Петрова",
        dateComment: "23.05.2024, 16:48",
      },
    ],
    URL: "../../assets/filterSection/video2.mp4",
  },
  {
    id: "23jsdfh49",
    type: "video",
    category: "Заштита на податоците",
    title: "Како да криптирате податоци на вашата веб страна",
    text: "Ова видео објаснува како да ги криптирате податоците на вашата веб страна за да ги заштитите од неовластен пристап или преглед.",
    datePosted: "28.04.2024",
    comments: [
      {
        comment: "Браво, одлично!",
        userImage: "../../assets/imgProfile/profile2.png",
        userName: "Марко Ангеловски",
        dateComment: "23.05.2024, 16:40",
      },
    ],
    URL: "../../assets/filterSection/video3.mp4",
  },
  {
    id: "65hdfg783",
    type: "video",
    category: "Основни безбедносни принципи",
    title: "Заштита на сесии и автентикација",
    text: "Ова видео ги дава најдобрите практики за заштита на сесии и заштита од неовластен пристап на вашата веб страница преку механизми за автентикација.",
    datePosted: "30.04.2024",
    comments: [
      {
        comment: "Одлично, страхотно!",
        userImage: "../../assets/imgProfile/profile13.png",
        userName: "Димитрија Ангелова",
        dateComment: "23.05.2024, 16:33",
      },
      {
        comment: "Фантастично, одлично изведено!",
        userImage: "../../assets/imgProfile/profile8.png",
        userName: "Андреа Тодорова",
        dateComment: "23.05.2024, 16:35",
      },
      {
        comment: "Прекрасно видео, уживај!",
        userImage: "../../assets/imgProfile/profile9.png",
        userName: "Милена Ѓорѓиева",
        dateComment: "23.05.2024, 16:38",
      },
    ],
    URL: "../../assets/filterSection/video7.mp4",
  },
  {
    id: "dhf43kjs",
    type: "article",
    category: "Заштита на податоците",
    title: "Заштита на приватноста онлајн",
    text: "За да ги заштитите своите приватни информации онлајн, користете приватен прелистувач, активирајте опциите за заштита на приватност и внимавајте кое информации го споделувате на социјалните мрежи.",
    datePosted: "08.04.2024",
    comments: [
      {
        comment: "Одлично, уживајте!",
        userImage: "../../assets/imgProfile/profile5.png",
        userName: "Милана Јованова",
        dateComment: "23.05.2024, 17:30",
      },
      {
        comment: "Браво, страхотно изведено!",
        userImage: "../../assets/imgProfile/profile11.png",
        userName: "Никола Милосевски",
        dateComment: "23.05.2024, 17:33",
      },
    ],
    URL: "../../assets/filterSection/6.jpg",
  },
  {
    id: "dsf9g78",
    type: "video",
    category: "Заштита од малвери и вируси",
    title: "Како да обновите безбедносни патчеви и ажурирања",
    text: "Ова видео ги дава советите за обновување на безбедносните патчеви и редовното ажурирање на вашата веб апликација за да се спречат безбедносни ризици.",
    datePosted: "02.05.2024",
    comments: [],
    URL: "../../assets/filterSection/video8.mp4",
  },
  {
    id: "jfhd674d",
    type: "video",
    category: "Заштита на податоците",
    title: "Управување со кориснички информации и приватност",
    text: "Ова видео објаснува како да ги управувате со корисничките информации и како да ги заштитите од кршење на приватноста и недозволен пристап.",
    datePosted: "05.05.2024",
    comments: [],
    URL: "../../assets/filterSection/video9.mp4",
  },
  {
    id: "kjhg54g",
    type: "article",
    category: "Заштита на податоците",
    title: "Како да создадете сигурни лозинки",
    text: "Сигурните лозинки се важен дел од заштитата на вашите податоци. Користете долги и сложени лозинки, користејќи различни карактери и избегнувајте користење на лични информации или предвидливи зборови.",
    datePosted: "10.04.2024",
    comments: [
      {
        comment: "Фантастично, одлично!",
        userImage: "../../assets/imgProfile/profile2.png",
        userName: "Ангела Иванова",
        dateComment: "23.05.2024, 17:35",
      },
      {
        comment: "Одлично, продолжете вака!",
        userImage: "../../assets/imgProfile/profile.png",
        userName: "Марко Јордановски",
        dateComment: "23.05.2024, 17:38",
      },
    ],
    URL: "../../assets/filterSection/5.jpg",
  },
  {
    id: "jdk32h6d",
    type: "video",
    category: "Основни безбедносни принципи",
    title: "Заштита на веб апликации од DDOS напади",
    text: "Ова видео дава насоки за заштита на вашата веб апликација од напади со одбивање на услуги (DDOS) кои можат да ја доведат до нефункционалност.",
    datePosted: "08.05.2024",
    comments: [
      {
        comment: "Фантастично видео, вистинско уживање!",
        userImage: "../../assets/imgProfile/profile9.png",
        userName: "Мартин Димитров",
        dateComment: "23.05.2024, 16:23",
      },
      {
        comment: "Одлично, браво!",
        userImage: "../../assets/imgProfile/profile10.png",
        userName: "Марија Јованова",
        dateComment: "23.05.2024, 16:25",
      },
      {
        comment: "Браво, совршено!",
        userImage: "../../assets/imgProfile/profile3.png",
        userName: "Никола Милановски",
        dateComment: "23.05.2024, 16:28",
      },
      {
        comment: "Фантастично, продолжете така!",
        userImage: "../../assets/imgProfile/profile7.png",
        userName: "Стефана Трајанова",
        dateComment: "23.05.2024, 16:30",
      },
    ],
    URL: "../../assets/filterSection/video5.mp4",
  },
  {
    id: "hjdfg657",
    type: "article",
    category: "Заштита од малвери и вируси",
    title: "Како да спречите инсталирање на злонамерен софтвер",
    text: "Инсталирањето на антивирусен софтвер и редовна проверка на системот се важни чекори за спречување на инфекции од малвери и вируси. Освен тоа, треба да бидете внимателни при преземање и инсталирање на софтвер, особено од непознати извори.",
    datePosted: "14.04.2024",
    comments: [
      {
        comment: "Браво, уживај!",
        userImage: "../../assets/imgProfile/profile4.png",
        userName: "Милена Трајчева",
        dateComment: "23.05.2024, 17:40",
      },
    ],
    URL: "../../assets/filterSection/3.jpg",
  },
  {
    id: "hjdsj765",
    type: "article",
    category: "Заштита од малвери и вируси",
    title: "Препознавање и справување со фишинг напади",
    text: "Фишинг нападите се обиди за преварање на корисниците за да добијат лични информации. За да се заштитите од нив, бидете внимателни при кликнување на непознати врски или давање на лични информации преку е-пошта.",
    datePosted: "12.04.2024",
    comments: [],
    URL: "../../assets/filterSection/4.jpg",
  },
  {
    id: "dsfhg92f",
    type: "video",
    category: "Заштита од малвери и вируси",
    title: "Заштита од социјални инжењерски напади",
    text: "Ова видео ги објаснува различните видови на социјални инжењерски напади и како да ги откриете и спречите.",
    datePosted: "11.05.2024",
    comments: [
      {
        comment: "Одлично, продолжете вака!",
        userImage: "../../assets/imgProfile/profile5.png",
        userName: "Ангела Петрова",
        dateComment: "23.05.2024, 16:20",
      },
    ],
    URL: "../../assets/filterSection/video6.mp4",
  },
  {
    id: "dhs9g324",
    type: "video",
    category: "Заштита на податоците",
    title: "Како да го спречите кршењето на сесии",
    text: "Ова видео објаснува како да ги спречите кршењето на сесии и да ги заштитите корисниците од неовластен пристап до нивните сесии.",
    datePosted: "14.05.2024",
    comments: [
      {
        comment: "Браво, вистински мајстори!",
        userImage: "../../assets/imgProfile/profile13.png",
        userName: "Кристијан Ѓорѓиев",
        dateComment: "23.05.2024, 16:18",
      },
    ],
    URL: "../../assets/filterSection/video1.mp4",
  },
  {
    id: "dhs924s7",
    type: "video",
    category: "Основни безбедносни принципи",
    title: "Како да ја спречите инјекција на скрипти",
    text: "Ова видео објаснува како да ги спречите (XSS) во вашата веб апликација за да ги заштитите корисниците од напади.",
    datePosted: "17.05.2024",
    comments: [
      {
        comment: "Фантастично, страхотно видео!",
        userImage: "../../assets/imgProfile/profile1.png",
        userName: "Ангела Николова",
        dateComment: "23.05.2024, 16:10",
      },
      {
        comment: "Одлично видео, уживај!",
        userImage: "../../assets/imgProfile/profile5.png",
        userName: "Никола Стефановски",
        dateComment: "23.05.2024, 16:12",
      },
      {
        comment: "Фантастично, одлично изведено!",
        userImage: "../../assets/imgProfile/profile.png",
        userName: "Милана Трајкова",
        dateComment: "23.05.2024, 16:15",
      },
    ],
    URL: "../../assets/filterSection/video2.mp4",
  },
  {
    id: "nskjkizx6asfz",
    type: "article",
    category: "Последни новости",
    title: "Најнови трендови во криптографијата",
    text: "Овој чланок ги истражува најновите трендови и иновации во областа на криптографијата, вклучувајќи ги и последните промени во стандардите и протоколите.",
    datePosted: "15.05.2024",
    comments: [
      {
        comment: "Неверојатно, ова видео е предобро",
        userImage: "../../assets/imgProfile/profile7.png",
        userName: "Н Илиевска",
        dateComment: "24.08.2023, 13:46",
      },
      {
        comment: "Неверојатно",
        userImage: "../../assets/imgProfile/profile1.png",
        userName: "Мирјана Алексовска",
        dateComment: "24.08.2023, 13:46",
      },
      {
        comment: "Така продолжи",
        userImage: "../../assets/imgProfile/profile8.png",
        userName: "Д Спасевски",
        dateComment: "24.08.2023, 13:46",
      },
    ],
    URL: "../../assets/filterSection/10.jpg",
  },
  {
    id: "d7g39f7s",
    type: "video",
    category: "Заштита од малвери и вируси",
    title: "Како да го детектирате и уклоните злонамерен код",
    text: "Ова видео објаснува како да детектирате и уклоните злонамерен код од вашата веб апликација за да ја заштитите од малверски напади.",
    datePosted: "20.05.2024",
    comments: [
      {
        comment: "Прекрасно, фантастично!",
        userImage: "../../assets/imgProfile/profile9.png",
        userName: "Марио Ангелов",
        dateComment: "23.05.2024, 16:05",
      },
      {
        comment: "Одлично, продолжи така!",
        userImage: "../../assets/imgProfile/profile7.png",
        userName: "Стефан Василев",
        dateComment: "23.05.2024, 16:07",
      },
    ],
    URL: "../../assets/filterSection/video4.mp4",
  },
  {
    id: "hag67sdsdgj",
    type: "article",
    category: "Последни новости",
    title: "Најновите разоткривања во областа на кибер безбедноста",
    text: "Овој чланок ги претставува најновите разоткривања и најголемите предизвици во областа на кибер безбедноста, вклучувајќи ги и актуелните законски промени.",
    datePosted: "07.05.2024",
    comments: [
      {
        comment: "Одлично, продолжете така!",
        userImage: "../../assets/imgProfile/profile5.png",
        userName: "Ивана Јорданова",
        dateComment: "23.05.2024, 17:18",
      },
      {
        comment: "Фантастично видео, уживајте!",
        userImage: "../../assets/imgProfile/profile4.png",
        userName: "Дарко Ангелов",
        dateComment: "23.05.2024, 17:20",
      },
      {
        comment: "Одлично, страхотно!",
        userImage: "../../assets/imgProfile/profile7.png",
        userName: "Марија Тодоровска",
        dateComment: "23.05.2024, 17:23",
      },
      {
        comment: "Браво, фантастично!",
        userImage: "../../assets/imgProfile/profile12.png",
        userName: "Петар Димитровски",
        dateComment: "23.05.2024, 17:25",
      },
    ],
    URL: "../../assets/filterSection/8.jpg",
  },
  {
    id: "f63jfdh4",
    type: "video",
    category: "Заштита на податоците",
    title: "Безбедносни мерки за заштита на кориснички информации",
    text: "Ова видео ги објаснува најдобрите безбедносни мерки за заштита на кориснички информации за да се спречат кршења на приватноста.",
    datePosted: "23.05.2024",
    comments: [
      {
        comment: "Фантастично, продолжи така!",
        userImage: "../../assets/imgProfile/profile4.png",
        userName: "Петар Јованов",
        dateComment: "23.05.2024, 16:00",
      },
      {
        comment: "Одлично видео, одлично изведено!",
        userImage: "../../assets/imgProfile/profile5.png",
        userName: "Јасмина Георгиева",
        dateComment: "23.05.2024, 16:02",
      },
    ],
    URL: "../../assets/filterSection/video7.mp4",
  },
  {
    id: "dhs72g3d",
    type: "video",
    category: "Основни безбедносни принципи",
    title: "Заштита на веб апликации од CSRF напади",
    text: "Ова видео дава совети за заштита на вашата веб апликација од напади со фалсификување на (CSRF) кои можат да ги злостават сесиите на корисниците.",
    datePosted: "26.05.2024",
    comments: [
      {
        comment: "Прекрасно, браво!",
        userImage: "../../assets/imgProfile/profile2.png",
        userName: "Елена Велковска",
        dateComment: "23.05.2024, 15:55",
      },
      {
        comment: "Вистинско задоволство, одлично!",
        userImage: "../../assets/imgProfile/profile3.png",
        userName: "Мартина Стефанова",
        dateComment: "23.05.2024, 15:57",
      },
    ],
    URL: "../../assets/filterSection/video3.mp4",
  },
  {
    id: "fjs8239f",
    type: "video",
    category: "Заштита од малвери и вируси",
    title: "Како да го надградите безбедносниот слој на вашата веб апликација",
    text: "Ова видео објаснува како да го надградите безбедносниот слој на вашата веб апликација за да се заштитите од различни видови на малверски напади.",
    datePosted: "29.05.2024",
    comments: [
      {
        comment: "Вистинска уживаница, фантастично!",
        userImage: "../../assets/imgProfile/profile8.png",
        userName: "Никола Симовски",
        dateComment: "23.05.2024, 15:47",
      },
      {
        comment: "Одлично видео, продолжи така!",
        userImage: "../../assets/imgProfile/profile10.png",
        userName: "Марија Тодорова",
        dateComment: "23.05.2024, 15:50",
      },
      {
        comment: "Фантастично, одлично!",
        userImage: "../../assets/imgProfile/profile11.png",
        userName: "Марко Димитров",
        dateComment: "23.05.2024, 15:52",
      },
    ],
    URL: "../../assets/filterSection/video5.mp4",
  },
  {
    id: "dhs82g46",
    type: "video",
    category: "Заштита на податоците",
    title: "Безбедносни аспекти на користењето на кукиси",
    text: "Ова видео ги објаснува безбедносните аспекти на користењето на (cookies) во вашата веб апликација и како да ги заштитите од злоставување.",
    datePosted: "01.06.2024",
    comments: [
      {
        comment: "Браво, одлично изведено!",
        userImage: "../../assets/imgProfile/profile1.png",
        userName: "Милена Петрова",
        dateComment: "23.05.2024, 15:40",
      },
      {
        comment: "Совршено!",
        userImage: "../../assets/imgProfile/profile7.png",
        userName: "Ангела Арсовска",
        dateComment: "23.05.2024, 15:42",
      },
      {
        comment: "Прекрасно видео!",
        userImage: "../../assets/imgProfile/profile9.png",
        userName: "Теодора Јорданова",
        dateComment: "23.05.2024, 15:45",
      },
    ],
    URL: "../../assets/filterSection/video6.mp4",
  },
  {
    id: "hd73fg32",
    type: "video",
    category: "Основни безбедносни принципи",
    title: "Како да го унапредите пристапот на вашата веб апликација",
    text: "Ова видео ги дава насоките за унапредување на пристапот и аутентикацијата на вашата веб апликација за подобра заштита на корисничките информации.",
    datePosted: "04.06.2024",
    comments: [],
    URL: "../../assets/filterSection/video1.mp4",
  },
  {
    id: "df83jsd7",
    type: "video",
    category: "Заштита од малвери и вируси",
    title: "Преглед на сигурносни алгоритми и хеширање",
    text: "Ова видео објаснува преглед на различни сигурносни алгоритми и методи за хеширање за да ги заштитите вашите податоци од неовластен пристап.",
    datePosted: "07.06.2024",
    comments: [],
    URL: "../../assets/filterSection/video8.mp4",
  },
  {
    id: "jhjhs6jhs",
    type: "video",
    category: "Најпопуларни",
    title: "Најновите трендови во безбедноста на интернет",
    text: "Ова видео ги истражува најновите трендови во областа на безбедноста на интернет и како да се заштитите од нив.",
    datePosted: "01.05.2024",
    comments: [
      {
        comment: "Одлично видео, фантастично!",
        userImage: "../../assets/imgProfile/profile4.png",
        userName: "Емилија Трајанова",
        dateComment: "23.05.2024, 15:37",
      },
    ],
    URL: "../../assets/filterSection/video7.mp4",
  },
  {
    id: "kjjkxz7sagbvx4",
    type: "video",
    category: "Последни новости",
    title: "Најнови информации за онлајн безбедност",
    text: "Ова видео ги претставува најновите информации и трендови во областа на онлајн безбедност и како да ги примените на вашите системи.",
    datePosted: "03.05.2024",
    comments: [
      {
        comment: "Одлично!",
        userImage: "../../assets/imgProfile/profile6.png",
        userName: "Андреј Мицковски",
        dateComment: "23.05.2024, 15:35",
      },
    ],
    URL: "../../assets/filterSection/video9.mp4",
  },
  {
    id: "fdhjg45h",
    type: "article",
    category: "Основни безбедносни принципи",
    title: "Заштита од XSS напади",
    text: "XSS нападите можат да доведат до извршување на злонамерен JavaScript код во корисничкиот прелистувач. За да се заштитите, секогаш филтрирајте и ескапирајте кориснички влез пред да го вметнете во HTML.",
    datePosted: "16.04.2024",
    comments: [],
    URL: "../../assets/filterSection/2.jpg",
  },
  {
    id: "sdlsd,s5sd4sdnzcm",
    type: "video",
    category: "Најпопуларни",
    title: "Како да избегнете социјални инженери",
    text: "Ова видео ви дава практични совети за избегнување на социјалните инженери и заштита на вашите лични податоци.",
    datePosted: "05.05.2024",
    comments: [
      {
        comment: "Браво, одлично изведено!",
        userImage: "../../assets/imgProfile/profile5.png",
        userName: "Стефанија Трајковска",
        dateComment: "23.05.2024, 15:30",
      },
      {
        comment: "Изумително видео, просто совршено!",
        userImage: "../../assets/imgProfile/profile2.png",
        userName: "Јован Димитриев",
        dateComment: "23.05.2024, 15:32",
      },
    ],
    URL: "../../assets/filterSection/video2.mp4",
  },
  {
    id: "jhsdh7hc8",
    type: "video",
    category: "Последни новости",
    title: "Најнови алатки за кибер безбедност",
    text: "Ова видео ги претставува најновите алатки и техники за подобрување на вашата кибер безбедност.",
    datePosted: "07.05.2024",
    comments: [
      {
        comment: "Фантастично видео, страхотно!",
        userImage: "../../assets/imgProfile/profile3.png",
        userName: "Марко Илиевски",
        dateComment: "23.05.2024, 15:28",
      },
    ],
    URL: "../../assets/filterSection/video1.mp4",
  },
  {
    id: "kjjhfgyjh",
    type: "video",
    category: "Најпопуларни",
    title: "Техники за заштита на приватноста на мобилни уреди",
    text: "Ова видео ги истражува најефективните техники и алатки за заштита на приватноста на вашите мобилни уреди од потенцијални напади и нарушувања.",
    datePosted: "10.05.2024",
    comments: [
      {
        comment: "Фантастично, одлично изведено!",
        userImage: "../../assets/imgProfile/profile8.png",
        userName: "Андрија Димитров",
        dateComment: "23.05.2024, 17:50",
      },
      {
        comment: "Одлично, продолжете така!",
        userImage: "../../assets/imgProfile/profile9.png",
        userName: "Марија Николова",
        dateComment: "23.05.2024, 17:53",
      },
      {
        comment: "Браво, фантастично!",
        userImage: "../../assets/imgProfile/profile6.png",
        userName: "Петар Стефанов",
        dateComment: "23.05.2024, 17:55",
      },
    ],
    URL: "../../assets/filterSection/video6.mp4",
  },
  {
    id: "sdhgdj673",
    type: "article",
    category: "Основни безбедносни принципи",
    title: "Заштита од SQL",
    text: "SQL се опасни напади кои можат да ги изложат вашите податоци на ризик. За да се заштитите од нив, користете параметризирани барања и избегнувајте динамичка генерација на SQL барања.",
    datePosted: "18.04.2024",
    comments: [
      {
        comment: "Фантастично, браво!",
        userImage: "../../assets/imgProfile/profile5.png",
        userName: "Стефан Ангеловски",
        dateComment: "23.05.2024, 17:43",
      },
      {
        comment: "Одлично, страхотно изведено!",
        userImage: "../../assets/imgProfile/profile6.png",
        userName: "Јасмина Петровска",
        dateComment: "23.05.2024, 17:45",
      },
      {
        comment: "Браво, продолжете вака!",
        userImage: "../../assets/imgProfile/profile7.png",
        userName: "Владимир Ангеловски",
        dateComment: "23.05.2024, 17:48",
      },
    ],
    URL: "../../assets/filterSection/1.jpg",
  },
];
